server.port=8081

# Importar configuración de un archivo local .env (opcional, no fallará si no existe)
spring.config.import=optional:file:.env[.properties]

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:default@gmail.com}
spring.mail.password=${MAIL_PASSWORD:default}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

telegram.bot.token=${TELEGRAM_BOT_TOKEN:default_token}
telegram.chat.id=${TELEGRAM_CHAT_ID:default_id}
